# Camera image, with pan-tilt-zoom values.
#
# Lorenzo Bianchi <lnz.bnc@gmail.com>
# Intelligent Systems Lab <isl.torvergata@gmail.com>
#
# February 21, 2022

# This is free software.
# You can redistribute it and/or modify this file under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This file is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this file; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.

# Current pan angle
float32 pan
bool pan_global

# Current tilt angle
float32 tilt
bool tilt_global

# Current zoom angle
float32 zoom
bool zoom_global

# Current focus
float32 focus
bool focus_global
