/ptz/camera_driver:
  ros__parameters:
    ip_address: '172.16.0.3'
    username: 'root'
    password: 'TorVergata2'
    pan0: 0.0
    publish_split: True
    timer_period: 0.2
    topic_axis_camera: 'stream'
    topic_command: 'command'
    topic_image_ptzf: 'axis_image'
    topic_ptzf: 'ptzf'
